source 'https://rubygems.org'

# Declare the ruby version for heroku.
ruby '2.3.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
#for file uploads
gem 'paperclip', '~> 4.1'
#for templating
gem 'slim-rails'
#authentication and session
gem 'devise'
#nested forms
gem 'cocoon'
#font awesome
gem 'font-awesome-rails', '~> 4.6', '>= 4.6.3.1'
#for amazon syncs
gem 'aws-sdk', '1.63.0'
gem 'asset_sync'
gem 's3_direct_upload'
#pagination
gem 'will_paginate'
#rack redirect
gem 'rack-host-redirect'
#app server
gem 'therubyracer', group: :production
gem 'protected_attributes'
gem 'newrelic_rpm'
gem 'activerecord-import'
group :production do
  gem 'rails_12factor'
  gem 'heroku-deflater'
  gem 'unicorn'
end
group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'better_errors'
  gem 'rack-mini-profiler'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end
gem 'switchery-rails'
gem 'tzinfo'
gem 'tzinfo-data'
